/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package radnik;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Biljana Nedic
 */
public class frmNoviRadnik2 extends javax.swing.JFrame {
private ArrayList org_jed;
private KontrolorRadnik k;
private String izabranElement="Lilly maloprodaja";
private DefaultTableModel tblModel;
private int sifraRkraj;//najveca trenutna sifra u tabeli zaposleni
private int sifraOJRkraj;//najveca trenutna sifra u tabeli zap_org_jedinica
private int sifraOJizbor=1;//sifra izabrane organizacione jedinice
boolean p;
private String selektovan="Radnik";
    /**
     * Creates new form frmNoviRadnik2
     */
    public frmNoviRadnik2() {
        initComponents();
         try{
        k=new KontrolorRadnik();
        org_jed=k.vratiOrgJedinice();       
        napuniKomboOrgJedinice(); /*Puni kombo box organizacione jedinice*/
        sifraRkraj=k.vratiPoslednjuSifruRadnika();
        sifraOJRkraj=k.vratiPoslednjuSifruZapOrgJed();
         
       
      }
       catch (Exception e)
        {JOptionPane.showMessageDialog(null,e.toString());
        System.out.println("greska1 kod frmNoviRadnik");}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setTitle("Novi radnik i organizaciona jedinica");
        setLocation(new java.awt.Point(350, 150));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ime i prezime", "Matični broj", "Radno mesto", "Organizaciona jedinica", "Adresa", "Mobilni telefon"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Organizaciona jedinica");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ime i prezime");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Matični broj");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Radno mesto");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Adresa");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Mobilni telefon");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "radnik", "direktor", "regionalni menadzer", "sekretarica", "farmaceut" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton1.setText("Dodaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox1, 0, 226, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jTextField1)
                        .addComponent(jTextField2)
                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField3)
                        .addComponent(jTextField4))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton1)))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        obrisiPodatkeTabele();
        izabranElement=jComboBox1.getSelectedItem().toString();
        System.out.println("izabran je "+izabranElement);
        try{
            int m=0;
            ArrayList tabela=k.vratiFiltriranoOrgJedinice(izabranElement);
          //  System.out.println("velicina tabele"+tabela.size());
            int brojRedova=tabela.size()/6;
            //System.out.println("broj redova"+brojRedova);
            String[] red=new String[6];
            tblModel=(DefaultTableModel) jTable1.getModel();
            for (int i = 0; i < brojRedova; i++) {
                for (int j = 0; j < 6; j++) {
                    red[j]=tabela.get(m).toString();
                    m++;
                }
                tblModel.addRow(red);
            }
        
             // postavljanje vrednosti za privatnu promenljivu sifraOJizbor
        switch(jComboBox1.getSelectedItem().toString()) {
            case "Lilly maloprodaja":sifraOJizbor=1;
                break;
            case "Lilly direkcija": sifraOJizbor=2;
                 break;
            case "Lilly kadrovska":sifraOJizbor=3;
                 break;          
            case "Lilly komercijala":sifraOJizbor=4;
                 break;
            case "Lilly farmaceut":sifraOJizbor=5;
                break;
            default:sifraOJizbor=1;
               break; 
        }
            System.out.println("izabrana sifra org jedinice je "+sifraOJizbor);
        }
    
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e);

    }//GEN-LAST:event_jComboBox1ActionPerformed
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // front
        String orgJed=jComboBox1.getSelectedItem().toString();
        System.out.println("izabrana org jedinica je "+orgJed);
        String radnoMesto=jComboBox2.getSelectedItem().toString();
        String imePrez=jTextField1.getText();
        String jmbg=jTextField2.getText();
        String adresa=jTextField3.getText();
        String mobilni=jTextField4.getText();
        Object row[]=new Object[6];
        row[0]=imePrez;
        row[1]=jmbg;
        row[2]=radnoMesto;
        row[3]=orgJed;
        row[4]=adresa;
        row[5]=mobilni;
        tblModel.addRow(row);
        
        //backend
        
         p= provera();
        try {
       
        if (p!=true)  
        {   //tabela radnik
            int polje1=sifraRkraj+1;//sifra
            String polje2=jTextField1.getText();//ime prezime
            String polje3=jTextField2.getText();//jmbg
            String polje4=selektovan;//pozicija
            String polje5=jTextField3.getText();//adresa
            String polje6=jTextField4.getText();//mobilni telefon
            //tabela zap_org_jed
            int polje1DrugaT=sifraOJRkraj+1;//zap_org_jed_id
            int polje2DrugaT=sifraOJizbor;//org_jed_id
            int polje3DrugaT=sifraRkraj+1;//zap_id
            
            
        
        boolean odg=k.SacuvajRadnika2Tabele(polje1,polje2,polje3,polje4,polje5,polje6,polje1DrugaT,polje2DrugaT,polje3DrugaT);
        //System.out.println("dosao do forme novog radnika "+odg);
        
        if (odg==true) JOptionPane.showMessageDialog(null,"Sistem je zapamtio radnika u okviru organizacione jedinice");
        //setVisible(false);
              }// if true
        else JOptionPane.showMessageDialog(null,"Sistem ne može da zapamti radnika i organizacionu jedinicu");
      }
      catch (Exception e)
      {JOptionPane.showMessageDialog(null,"Sistem ne može da kreira novog radnika u okviru organizacione jedinice "+e.toString());
        
      }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        selektovan=jComboBox2.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBox2ActionPerformed
     private boolean provera(){
      p=false;    
      if (jTextField1.getText().equals("") || jTextField2.getText().equals("") || jTextField3.getText().equals("") || jTextField4.getText().equals("")) p=true;
      return(p);
      };//Provera da neko polje nije prazno
    public void obrisiPodatkeTabele(){
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.setRowCount(0);

}
    public void napuniKomboOrgJedinice()/*puni kombo box iz tabele org_jedinica*/
 {
     String pom[];
      for (int i=0;i<org_jed.size();)
  { 
    pom=new String[1];
    pom=(String[])org_jed.get(i); 
     jComboBox1.addItem(pom[0]);
      System.out.println("i je "+i+"organizaciona jedinica je"+pom[0]);
      i++;
  }}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNoviRadnik2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNoviRadnik2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNoviRadnik2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNoviRadnik2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNoviRadnik2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
