/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package radnik;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Biljana Nedic
 */
public class frmOrgJedinica extends javax.swing.JFrame {
private ArrayList org_jed;
private KontrolorRadnik k;
String izabranElement="Lilly maloprodaja";
    /**
     * Creates new form frmOrgJedinica
     */

    public frmOrgJedinica() {
        initComponents();
       
        try{
        k=new KontrolorRadnik();
        org_jed=k.vratiOrgJedinice();
        napuniKomboOrgJedinice(); /*Puni kombo box organizacione jedinice*/
       
      }
       catch (Exception e)
        {JOptionPane.showMessageDialog(null,"Sistem ne može da prikaže tabelu zaposlenih radnika u okviru organizacione jedinice");
        System.out.println("greska1 kod frmNoviRadnik");}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();

        setTitle("Prikazi radnike po organizacionim jedinicma");
        setLocation(new java.awt.Point(350, 150));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ime i prezime", "Maticni broj", "Radno mesto", "Organizaciona jedinica", "Adresa", "Mobilni telefon"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Organizaciona jedinica");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       
       /*    
             try{
           int m=0; 
          ArrayList tabela=k.PrikaziRadnikePoOrgJedinicama();
          System.out.println("velicina tabele"+tabela.size());
          int brojRedova=tabela.size()/6;
          System.out.println("broj redova"+brojRedova);
          String[] red=new String[6];
          DefaultTableModel tblModel=(DefaultTableModel) jTable1.getModel();
               for (int i = 0; i < brojRedova; i++) {
                   for (int j = 0; j < 6; j++) {
                       red[j]=tabela.get(m).toString();
                       m++;
                   }
                 tblModel.addRow(red); 
               }   
            }
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e);
        }*/
    }//GEN-LAST:event_formWindowOpened

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        obrisiPodatkeTabele();
        izabranElement=jComboBox1.getSelectedItem().toString();
        System.out.println("izabran je "+izabranElement);
        try{
           int m=0; 
          ArrayList tabela=k.vratiFiltriranoOrgJedinice(izabranElement);
          System.out.println("velicina tabele"+tabela.size());
          int brojRedova=tabela.size()/6;
          System.out.println("broj redova"+brojRedova);
          String[] red=new String[6];
          DefaultTableModel tblModel=(DefaultTableModel) jTable1.getModel();
               for (int i = 0; i < brojRedova; i++) {
                   for (int j = 0; j < 6; j++) {
                       red[j]=tabela.get(m).toString();
                       m++;
                   }
                 tblModel.addRow(red); 
               }   
            }
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e);
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed
    }    
public void obrisiPodatkeTabele(){
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.setRowCount(0);

}
    public void napuniKomboOrgJedinice()/*puni kombo box iz tabele org_jedinica*/
 {
     String pom[];
      for (int i=0;i<org_jed.size();)
  { 
    pom=new String[1];
    pom=(String[])org_jed.get(i); 
     jComboBox1.addItem(pom[0]);
      i++;
  }}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmOrgJedinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmOrgJedinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmOrgJedinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmOrgJedinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmOrgJedinica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
