/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package radnik;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Biljana
 */
public class frmPrikaziFakture extends javax.swing.JFrame {
private KontrolorFaktura f;
private KontrolorRadnik k;
private ArrayList niz;
private String fakturaDefault;
private String izabranElement;
private ArrayList imePrez;
String imeRadnika=null;

    /**
     * Creates new form frmPrikaziFakture
     */
    public frmPrikaziFakture() {
        initComponents();
        try{
        f=new KontrolorFaktura();
        k=new KontrolorRadnik();
       niz=f.vratiFaktureFrmPrikaziFakture();
       fakturaDefault=niz.get(0).toString(); //default faktura je prva ucitana u array listi
       //napuniKomboFakture();
       AutoCompleteDecorator.decorate(jComboBox1);
       imePrez=k.vratiImeISifruRadnika();
     
      }
       catch (Exception e)
        {JOptionPane.showMessageDialog(null,e.toString());
        System.out.println("greska1 kod frmPrikaziFakture");}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pregled faktura");
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Faktura:");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rbr.", "Id zaposlenog", "Cena"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        obrisiPodatkeTabele();
        izabranElement=jComboBox1.getSelectedItem().toString();
        try{
           int m=0;
           
          ArrayList tabela=f.PrikaziStavkeFakture(izabranElement);
              //System.out.println(k.vratiImePomocuSifre(Integer.parseInt(tabela.get(1).toString())));
             
          System.out.println("velicina tabele"+tabela.size());
          int brojRedova=tabela.size()/3;
          String[] red=new String[3];
          DefaultTableModel tblModel=(DefaultTableModel) jTable1.getModel();
               for (int i = 0; i < brojRedova; i++) {
                 
                   for (int j = 0; j < 3; j++) {                       
                       if(j==1){
                           String im=tabela.get(m).toString();
                           red[1]=k.vratiImePomocuSifre(Integer.parseInt(im));//popunjavanje imana radnika na osnovu sifre
                       
                       }
                       else
                       red[j]=tabela.get(m).toString();    
                    m++;
                   }
                 tblModel.addRow(red); 
               }  
            }
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e);
        }
         
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        napuniKomboFakture();
        obrisiPodatkeTabele();
          try{
           int m=0;
           
          ArrayList tabela=f.PrikaziStavkeFakture(izabranElement);
              //System.out.println(k.vratiImePomocuSifre(Integer.parseInt(tabela.get(1).toString())));
             
          System.out.println("velicina tabele"+tabela.size());
          int brojRedova=tabela.size()/3;
          String[] red=new String[3];
          DefaultTableModel tblModel=(DefaultTableModel) jTable1.getModel();
               for (int i = 0; i < brojRedova; i++) {
                 
                   for (int j = 0; j < 3; j++) {                       
                       if(j==1){
                           String im=tabela.get(m).toString();
                           red[1]=k.vratiImePomocuSifre(Integer.parseInt(im));//popunjavanje imana radnika na osnovu sifre
                       
                       }
                       else
                       red[j]=tabela.get(m).toString();    
                    m++;
                   }
                 tblModel.addRow(red); 
               }  
            }
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
            
    }//GEN-LAST:event_formWindowOpened
public void napuniKomboFakture()/*puni kombo box iz tabele org_jedinica*/
 {
     String pom="";
      for (int i=0;i<niz.size();)
  { 
    pom=niz.get(i).toString(); 
     jComboBox1.addItem(pom);
     i++;
  }}

public void obrisiPodatkeTabele(){
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.setRowCount(0);

}

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrikaziFakture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrikaziFakture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrikaziFakture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrikaziFakture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrikaziFakture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
