/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package radnik;

import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Biljana Nedic
 */
public class frmPromeniRadnika2 extends javax.swing.JFrame {
private ArrayList org_jed;
private KontrolorRadnik k;
private String izabranElement="Lilly maloprodaja";
private DefaultTableModel tblModel;
private int sifraRselektovan;//selektovana sifra u tabeli zaposleni
//private int sifraOJRkraj;//najveca trenutna sifra u tabeli zap_org_jedinica
//private int sifraOJizbor;//sifra izabrane organizacione jedinice
boolean p;
private String selektovan="Radnik";
String staraOrgJedStr;

    /**
     * Creates new form frmPromeniRadnika2
     */
    public frmPromeniRadnika2() {
        initComponents();
        try{
        k=new KontrolorRadnik();
      
       
       
      }
       catch (Exception e)
        {JOptionPane.showMessageDialog(null,"Sistem ne može da prikaže tabelu zaposlenih radnika u okviru organizacione jedinice");
        System.out.println("greska1 kod frmNoviRadnik");}
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();

        setTitle("Promeni radnika i organizacionu jedinicu");
        setLocation(new java.awt.Point(350, 150));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Organizaciona jedinica");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ime i prezime");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Matični broj");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Radno mesto");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Adresa");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Mobilni telefon");

        jTextField4.setToolTipText("");
        jTextField4.setName(""); // NOI18N

        jButton1.setText("Promeni");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Šifra", "Ime i prezime", "Matični broj", "Radno mesto", "Organizaciona jedinica", "Adresa", "Mobilni telefon"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jTextField5.setToolTipText("");
        jTextField5.setName(""); // NOI18N

        jTextField6.setToolTipText("");
        jTextField6.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jTextField1)
                        .addComponent(jTextField2)
                        .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModelpromena=(DefaultTableModel) jTable2.getModel();
        String polje0=tblModelpromena.getValueAt(jTable2.getSelectedRow(), 0).toString();//sifra selektovanog radnika
        sifraRselektovan=Integer.parseInt(polje0);
        String polje1=tblModelpromena.getValueAt(jTable2.getSelectedRow(), 1).toString();
        String polje2=tblModelpromena.getValueAt(jTable2.getSelectedRow(), 2).toString();
        String polje3=tblModelpromena.getValueAt(jTable2.getSelectedRow(), 4).toString();//stara org jedinica
        String polje4=tblModelpromena.getValueAt(jTable2.getSelectedRow(), 3).toString();
        String polje5=tblModelpromena.getValueAt(jTable2.getSelectedRow(), 5).toString();
        String polje6=tblModelpromena.getValueAt(jTable2.getSelectedRow(), 6).toString();
        jTextField1.setText(polje1);
        jTextField2.setText(polje2);
        jTextField3.setText(polje3);
        jTextField4.setText(polje4);
        jTextField5.setText(polje5);
        jTextField6.setText(polje6);
        staraOrgJedStr=polje3;
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
             try{
        String promena1=jTextField1.getText();//ime i prezime
        String promena2=jTextField2.getText();//jmbg
        String promena3=jTextField3.getText();//organizaciona jedinica   
                
        String promena4=jTextField4.getText();//radno mesto
        String promena5=jTextField5.getText();//adresa
        String promena6=jTextField6.getText();//mobilni
        
        int staraOrgJed=vratiSifruOrgJedinice(staraOrgJedStr);//STARA org jedinica
       

// podaci za drugu tabelu
      //  int polje1DrugaT=sifraOJRkraj+1;//zap_org_jed_id
        int novaOrgJed=vratiSifruOrgJedinice(promena3);//org_jed_id NOVA
        int zapIdZamena=sifraRselektovan;//zap_id
                System.out.println("Stara org jedinica sifra"+staraOrgJed);
                System.out.println("Nova org jedinica sifra"+novaOrgJed);
                System.out.println("sifra radnika"+zapIdZamena);
        int sifraZamene=k.vratiZapOrgJedId(staraOrgJed,zapIdZamena);  //zap_org_jed_id   
       
                 System.out.println("sifra zamene za drugu tabelu"+sifraZamene);
                 
        boolean odg=k.PromeniRadnika2(zapIdZamena,promena1,promena2,promena4,promena5,promena6,sifraZamene,novaOrgJed,zapIdZamena);
        obrisiPodatkeTabele();        
        popuniTabelu();
     
        if (odg==true) JOptionPane.showMessageDialog(null,"Sistem je zapamtio radnika i organizacionu jedinicu.","Poruka",JOptionPane.PLAIN_MESSAGE);
       
       //setVisible(false);
              }// if true  */   
             catch (Exception e)
      {JOptionPane.showMessageDialog(null,"Sistem ne može da zapamti radnika i pripadajuću organizacionu jedinicu "+e.toString());
    }//GEN-LAST:event_jButton1ActionPerformed
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        obrisiPodatkeTabele();
        popuniTabelu();                                 
    }//GEN-LAST:event_formWindowOpened

    public void popuniTabelu(){
            
        try{
           int m=0; 
          ArrayList tabela=k.vratiRadnikeSaSifrom();
          System.out.println("velicina tabele"+tabela.size());
          int brojRedova=tabela.size()/7;
          System.out.println("broj redova"+brojRedova);
          String[] red=new String[7];
          DefaultTableModel tblModel=(DefaultTableModel) jTable2.getModel();
               for (int i = 0; i < brojRedova; i++) {
                   for (int j = 0; j < 7; j++) {
                       red[j]=tabela.get(m).toString();
                       m++;
                   }
                 tblModel.addRow(red); 
               }   
            }
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e);
        
        
    } 
    
    
    }
public void obrisiPodatkeTabele(){
DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
model.setRowCount(0);

}
public int vratiSifruOrgJedinice(String polje){
    int sifraOJizbor=1;
 switch(polje) {
            case "Lilly maloprodaja":sifraOJizbor=1;
                break;
            case "Lilly direkcija": sifraOJizbor=2;
                 break;
            case "Lilly kadrovska":sifraOJizbor=3;
                 break;          
            case "Lilly komercijala":sifraOJizbor=4;
                 break;
            case "Lilly farmaceut":sifraOJizbor=5;
                break;
            default:sifraOJizbor=1;
               break; 
        }
return sifraOJizbor;

}
  
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPromeniRadnika2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPromeniRadnika2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPromeniRadnika2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPromeniRadnika2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPromeniRadnika2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
